apiVersion: apps/v1
kind: Deployment
metadata:
  name:  redis
  labels:
    app:  redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app:  redis
    spec:
      containers:
      - name:  redis
        image:  redis
        ports:
        - containerPort:  6379
          name:  redis
---
apiVersion: v1
kind: Service
metadata:
  name: loadbalance
spec:
  type: LoadBalancer
  ports:
  - port: 6379
  selector:
    app: redis