apiVersion: apps/v1
kind: Deployment
metadata:
  name: voteapp
  labels:
    app: voteapp
spec:
  selector:
    matchLabels:
      app: voteapp
  replicas: 1
  template:
    metadata:
      labels:
        app: voteapp
    spec:
      containers:
      - name: voteapp
        image: whujin11e/public:azure_voting_app
        ports:
        - containerPort: 80
        env:
        - name: REDIS
          value: "redis"
        - name: STRESS_SECS
          value: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: voteapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: voteapp